const { getVariant } = require("./process");
const { getColors } = require("./primer");

function getTheme({ style, name }) {
  // Usage: `auto('pink')`
  const auto = (hex) => getVariant(hex, style);

  // Usage: `pick({ light: "lightblue", dark: "darkblue" })`
  const pick = (options) => options[style];

  const primer = getColors(style);

  const workbenchForeground = pick({ light: primer.gray[8], dark: primer.gray[7] });
  const editorForeground = pick({ light: primer.gray[9], dark: primer.gray[7] });

  return {
    name: name,
    colors: {
      focusBorder: pick({ light: primer.blue[4], dark: primer.blue[3] }),
      foreground: pick({ light: primer.gray[7], dark: primer.gray[6] }),
      descriptionForeground: primer.gray[5],
      errorForeground: primer.red[6],


      "activityBar.activeBackground": "#171717",
      "activityBar.activeBorder": "#027b3287",
      "activityBar.activeFocusBorder": "#fdfbfd",
      "activityBar.background": "#171717",
      "activityBar.border": "#232323",
      "activityBar.dropBorder": "#fbfbfd",
      "activityBar.foreground": "#027b3287",
      "activityBar.inactiveForeground": "#494949",
      "activityBarBadge.background": "#027b3286",
      "activityBarBadge.foreground": "#ffffff",

      "badge.background": "#2f00ff3b",
      "badge.foreground": "#fbfbfd",

      "banner.background": "#027b3287",
      "banner.foreground": "#171717",
      "banner.iconForeground": "#027b3287",

      "breadcrumb.activeSelectionForeground": "#fbfbfd",
      "breadcrumb.background": "#171717",
      "breadcrumb.focusForeground": "#fbfbfd",
      "breadcrumb.foreground": "#fbfbfd",
      "breadcrumbPicker.background": "#232323",

      "button.background": "#027b3287",
      "button.border": "#027b3287",
      "button.foreground": "#fbfbfd",
      "button.hoverBackground": "#027b3258",
      "button.secondaryBackground": "#027b327e",
      "button.secondaryForeground": "#fbfbfd",
      "button.secondaryHoverBackground": "#027b3287",
      "button.separator": "#fbfbfd",

      "charts.blue": "#0000ff",
      "charts.foreground": "#fbfbfd",
      "charts.green": "#027b32",
      "charts.lines": "#fbfbfd",
      "charts.orange": "#ff6b02",
      "charts.purple": "#8800ff",
      "charts.red": "#be0000",
      "charts.yellow": "#fff700",

      "checkbox.background": "#232323",
      "checkbox.border": "#fbfbfd7e",
      "checkbox.foreground": "#fbfbfd7e",

      "commandCenter.activeBackground": "#027b3287",
      "commandCenter.activeForeground": "#fbfbfd",
      "commandCenter.background": "#171717",
      "commandCenter.border": "#232323",
      "commandCenter.foreground": "#fbfbfd6b",

      "contrastActiveBorder": "#232323",
      "contrastBorder": "#232323",

      "debugExceptionWidget.background": "#171717",
      "debugExceptionWidget.border": "#232323",

      "debugTokenExpression.boolean": "#fbfbfd",
      "debugTokenExpression.error": "#fbfbfd",
      "debugTokenExpression.name": "#fbfbfd",
      "debugTokenExpression.number": "#fbfbfd",
      "debugTokenExpression.string": "#fbfbfd",
      "debugTokenExpression.value": "#fbfbfd",

      "debugToolBar.background": "#ff0000",
      "debugToolBar.border": "#232323",

      "debugView.exceptionLabelBackground": "#171717",
      "debugView.exceptionLabelForeground": "#fbfbfd",
      "debugView.stateLabelBackground": "#171717",
      "debugView.stateLabelForeground": "#fbfbfd",
      "debugView.valueChangedHighlight": "#fbfbfd",

			"descriptionForeground": "#fbfbfd",

      "diffEditor.border": "#232323",
      "diffEditor.diagonalFill": "#fbfbfd46",
      "diffEditor.insertedLineBackground": "#027b3287",
      "diffEditor.insertedTextBackground": "#027b3287",
      "diffEditor.insertedTextBorder": "#027b3287",
      "diffEditor.removedLineBackground": "#be00001c",
      "diffEditor.removedTextBackground": "#be00004c",
      "diffEditor.removedTextBorder": "#be00004c",
      "diffEditorGutter.insertedLineBackground": "#027b3287",
      "diffEditorGutter.removedLineBackground": "#be00001c",
      "diffEditorOverview.insertedForeground": "#027b3287",
      "diffEditorOverview.removedForeground": "#be00001c",

    "disabledForeground": "#ddff02",

		"dropdown.background": "#232323",
		"dropdown.border": "#232323",
		"dropdown.foreground": "#fbfbfd",
		"dropdown.listBackground": "#232323",
    
		"editor.background": "#171717",
		"editor.findMatchBackground": "#027b3259",
		"editor.findMatchBorder": "#055b045c",
		"editor.findMatchHighlightBackground": "#027b3238",
		"editor.findMatchHighlightBorder": "#027b321e",
		"editor.findRangeHighlightBackground": "#027b323a",
		"editor.findRangeHighlightBorder": "#027b3244",
		"editor.focusedStackFrameHighlightBackground": "#027b3287",
		"editor.foldBackground": "#23232370",
		"editor.foreground": "#fbfbfda3",
		"editor.hoverHighlightBackground": "#00ffc82b",
		"editor.inactiveSelectionBackground": "#2323237e",
		"editor.inlineValuesBackground": "#027b32",
		"editor.inlineValuesForeground": "#fbfbfd",
		"editor.lineHighlightBackground": "#00ff3715",
		"editor.lineHighlightBorder": "#fbfbfd1b",
		"editor.linkedEditingBackground": "#e6ff013f",
		"editor.rangeHighlightBackground": "#027b323a",
		"editor.rangeHighlightBorder": "#027b3287",
		"editor.selectionBackground": "#fbfbfd15",
		"editor.selectionForeground": "#2600ff",
		"editor.selectionHighlightBackground": "#53c80a29",
		"editor.selectionHighlightBorder": "#232323",
		"editor.snippetFinalTabstopHighlightBackground": "#171717",
		"editor.snippetFinalTabstopHighlightBorder": "#232323",
		"editor.snippetTabstopHighlightBackground": "#171717",
		"editor.snippetTabstopHighlightBorder": "#232323",
		"editor.stackFrameHighlightBackground": "#fbfbfd73",
		"editor.symbolHighlightBackground": "#4800ff70",
		"editor.symbolHighlightBorder": "#4800ffac",
		"editor.wordHighlightBackground": "#027b3287",
		"editor.wordHighlightBorder": "#2323236f",
		"editor.wordHighlightStrongBackground": "#027b327a",
		"editor.wordHighlightStrongBorder": "#2323236f",
		"editorBracketHighlight.foreground1": "#fd01f9",
		"editorBracketHighlight.foreground2": "#00d4fe",
		"editorBracketHighlight.foreground3": "#ff0077",
		"editorBracketHighlight.foreground4": "#00f2ff",
		"editorBracketHighlight.foreground5": "#fbf701",
		"editorBracketHighlight.foreground6": "#23fd01",
		"editorBracketHighlight.unexpectedBracket.foreground": "#ff2c6d",
		"editorBracketMatch.background": "#444444",
		"editorBracketMatch.border": "#444444",
		"editorBracketPairGuide.activeBackground1": "#fd01f9a7",
		"editorBracketPairGuide.activeBackground2": "#00d4fea7",
		"editorBracketPairGuide.activeBackground3": "#ff0077a7",
		"editorBracketPairGuide.activeBackground4": "#00f2ffa7",
		"editorBracketPairGuide.activeBackground5": "#fbf701a7",
		"editorBracketPairGuide.activeBackground6": "#23fd01a7",
		"editorBracketPairGuide.background1": "#fd01f9a7",
		"editorBracketPairGuide.background2": "#00d4fea7",
		"editorBracketPairGuide.background3": "#ff0077a7",
		"editorBracketPairGuide.background4": "#00f2ffa7",
		"editorBracketPairGuide.background5": "#fbf701a7",
		"editorBracketPairGuide.background6": "#23fd01a7",
		"editorCodeLens.foreground": "#fbfbfd",
		"editorCommentsWidget.rangeActiveBackground": "#232323",
		"editorCommentsWidget.rangeActiveBorder": "#232323",
		"editorCommentsWidget.rangeBackground": "#027b32",
		"editorCommentsWidget.rangeBorder": "#232323",
		"editorCommentsWidget.resolvedBorder": "#fbfbfd",
		"editorCommentsWidget.unresolvedBorder": "#fbfbfd",
		"editorCursor.background": "#232323",
		"editorCursor.foreground": "#027b32",
		"editorError.background": "#be000040",
		"editorError.border": "#be0000",
		"editorError.foreground": "#be000056",
		"editorGhostText.background": "#027b32",
		"editorGhostText.border": "#027b3287",
		"editorGhostText.foreground": "#02eafb",
		"editorGroup.border": "#232323",
		"editorGroup.dropBackground": "#027b3247",
		"editorGroup.dropIntoPromptBackground": "#171717",
		"editorGroup.dropIntoPromptBorder": "#232323",
		"editorGroup.dropIntoPromptForeground": "#fbfbfd",
		"editorGroup.emptyBackground": "#171717",
		"editorGroup.focusedEmptyBorder": "#232323",
		"editorGroupHeader.border": "#232323",
		"editorGroupHeader.noTabsBackground": "#171717",
		"editorGroupHeader.tabsBackground": "#171717",
		"editorGroupHeader.tabsBorder": "#232323",
		"editorGutter.addedBackground": "#023c87",
		"editorGutter.background": "#171717",
		"editorGutter.commentRangeForeground": "#878787",
		"editorGutter.deletedBackground": "#be0000",
		"editorGutter.foldingControlForeground": "#fbfbfd",
		"editorGutter.modifiedBackground": "#027b32",
		"editorHint.border": "#027b32",
		"editorHint.foreground": "#fbfbfd",
		"editorHoverWidget.background": "#232323",
		"editorHoverWidget.border": "#232323",
		"editorHoverWidget.foreground": "#fbfbfd",
		"editorHoverWidget.highlightForeground": "#027b32",
		"editorHoverWidget.statusBarBackground": "#be00000e",
		"editorIndentGuide.activeBackground": "#ff00dd13",
		"editorIndentGuide.background": "#232323",
		"editorInfo.background": "#17171700",
		"editorInfo.border": "#0a059483",
		"editorInfo.foreground": "#0054fb",
		"editorInlayHint.background": "#232323",
		"editorInlayHint.foreground": "#fbfbfd",
		"editorInlayHint.parameterBackground": "#232323",
		"editorInlayHint.parameterForeground": "#018796",
		"editorInlayHint.typeBackground": "#232323",
		"editorInlayHint.typeForeground": "#04ffe2",
		"editorLightBulb.foreground": "#f2ff03",
		"editorLightBulbAutoFix.foreground": "#027b3287",
		"editorLineNumber.activeForeground": "#027b32",
		"editorLineNumber.foreground": "#fbfbfd48",
		"editorLink.activeForeground": "#043e9b",
		"editorMarkerNavigation.background": "#171717",
		"editorMarkerNavigationError.background": "#be000086",
		"editorMarkerNavigationError.headerBackground": "#be00009d",
		"editorMarkerNavigationInfo.background": "#010a807f",
		"editorMarkerNavigationInfo.headerBackground": "#171717",
		"editorMarkerNavigationWarning.background": "#8840018f",
		"editorMarkerNavigationWarning.headerBackground": "#8840018f",
		"editorOverviewRuler.addedForeground": "#0000f8",
		"editorOverviewRuler.background": "#232323",
		"editorOverviewRuler.border": "#027b32",
		"editorOverviewRuler.bracketMatchForeground": "#9500ff8c",
		"editorOverviewRuler.commonContentForeground": "#fbfbfd",
		"editorOverviewRuler.currentContentForeground": "#027b3287",
		"editorOverviewRuler.deletedForeground": "#f7ff028c",
		"editorOverviewRuler.errorForeground": "#be00008c",
		"editorOverviewRuler.findMatchForeground": "#027b32",
		"editorOverviewRuler.incomingContentForeground": "#fbfbfd",
		"editorOverviewRuler.infoForeground": "#00b3ff8c",
		"editorOverviewRuler.modifiedForeground": "#15ee018c",
		"editorOverviewRuler.rangeHighlightForeground": "#027b324a",
		"editorOverviewRuler.selectionHighlightForeground": "#027b3287",
		"editorOverviewRuler.warningForeground": "#ff73008c",
		"editorOverviewRuler.wordHighlightForeground": "#027b3287",
		"editorOverviewRuler.wordHighlightStrongForeground": "#027b3287",
		"editorPane.background": "#027b32",
		"editorRuler.foreground": "#02660467",
		"editorStickyScroll.background": "#232323",
		"editorStickyScrollHover.background": "#171717",
		"editorSuggestWidget.background": "#232323",
		"editorSuggestWidget.border": "#232323",
		"editorSuggestWidget.focusHighlightForeground": "#fbfbfd",
		"editorSuggestWidget.foreground": "#fbfbfd",
		"editorSuggestWidget.highlightForeground": "#fbfbfd",
		"editorSuggestWidget.selectedBackground": "#232323",
		"editorSuggestWidget.selectedForeground": "#fbfbfd",
		"editorSuggestWidget.selectedIconForeground": "#fbfbfd",
		"editorSuggestWidgetStatus.foreground": "#0351f8",
		"editorUnicodeHighlight.background": "#027b3287",
		"editorUnicodeHighlight.border": "#027b3287",
		"editorUnnecessaryCode.border": "#232323",
		"editorUnnecessaryCode.opacity": "#be000093",
		"editorWarning.background": "#ff770000",
		"editorWarning.border": "#ff770037",
		"editorWarning.foreground": "#be0000",
		"editorWhitespace.foreground": "#e200e6",
		"editorWidget.background": "#171717",
		"editorWidget.border": "#232323",
		"editorWidget.foreground": "#fbfbfd72",
		"editorWidget.resizeBorder": "#027b32",


		"errorForeground": "#be0000",

		"extensionBadge.remoteBackground": "#027b3287",
		"extensionBadge.remoteForeground": "#fbfbfd",

		"extensionButton.prominentBackground": "#027b3287",
		"extensionButton.prominentForeground": "#fbfbfd",
		"extensionButton.prominentHoverBackground": "#027b3257",

		"extensionIcon.preReleaseForeground": "#ff9203",
		"extensionIcon.sponsorForeground": "#7700ff",
		"extensionIcon.starForeground": "#ffe600",
		"extensionIcon.verifiedForeground": "#0090fe",

		"focusBorder": "#232323",
		"foreground": "#fbfbfd7d",

		"gitDecoration.addedResourceForeground": "#027b32",
		"gitDecoration.conflictingResourceForeground": "#fe8301",
		"gitDecoration.deletedResourceForeground": "#be0000",
		"gitDecoration.ignoredResourceForeground": "#9f4500",
		"gitDecoration.modifiedResourceForeground": "#0090fe",
		"gitDecoration.renamedResourceForeground": "#fbfbfd",
		"gitDecoration.stageDeletedResourceForeground": "#00557d",
		"gitDecoration.stageModifiedResourceForeground": "#018403",
		"gitDecoration.submoduleResourceForeground": "#232323",
		"gitDecoration.untrackedResourceForeground": "#fbfbfd89",

		"icon.foreground": "#fbfbfd",

		"input.background": "#171717",
		"input.border": "#232323",
		"input.foreground": "#fbfbfda5",
		"input.placeholderForeground": "#fbfbfda5",
		"inputOption.activeBackground": "#474747a5",
		"inputOption.activeBorder": "#232323a5",
		"inputOption.activeForeground": "#fbfbfd65",
		"inputOption.hoverBackground": "#fbfbfda5",
		"inputValidation.errorBackground": "#be0000",
		"inputValidation.errorBorder": "#be0000",
		"inputValidation.errorForeground": "#be0000",
		"inputValidation.infoBackground": "#be00008b",
		"inputValidation.infoBorder": "#232323",
		"inputValidation.infoForeground": "#fbfbfd",
		"inputValidation.warningBackground": "#0d00c283",
		"inputValidation.warningBorder": "#be000084",
		"inputValidation.warningForeground": "#be000074",

		"keybindingLabel.border": "#232323",
		"keybindingLabel.bottomBorder": "#027b32",
		"keybindingLabel.foreground": "#027b3287",

		"keybindingTable.headerBackground": "#171717",
		"keybindingTable.rowsBackground": "#232323",

		"list.activeSelectionBackground": "#232323",
		"list.activeSelectionForeground": "#fbfbfd",
		"list.activeSelectionIconForeground": "#027b32",
		"list.deemphasizedForeground": "#ffcc01",
		"list.dropBackground": "#067a0042",
		"list.errorForeground": "#be0000ae",
		"list.filterMatchBackground": "#027b3228",
		"list.filterMatchBorder": "#027b32",
		"list.focusAndSelectionOutline": "#027b3280",
		"list.focusBackground": "#027b3287",
		"list.focusForeground": "#fbfbfd",
		"list.focusHighlightForeground": "#027b3275",
		"list.focusOutline": "#027b3287",
		"list.highlightForeground": "#fbfbfd",
		"list.hoverBackground": "#027b3243",
		"list.hoverForeground": "#fbfbfd",
		"list.inactiveFocusBackground": "#027b321e",
		"list.inactiveFocusOutline": "#027b321e",
		"list.inactiveSelectionBackground": "#0483023f",
		"list.inactiveSelectionForeground": "#fbfbfd",
		"list.inactiveSelectionIconForeground": "#027b32",
		"list.invalidItemForeground": "#be0000ae",
		"list.warningForeground": "#ff8801",
		"listFilterWidget.background": "#0010f5",
		"listFilterWidget.noMatchesOutline": "#6a6066",
		"listFilterWidget.outline": "#0000ff7c",
		"listFilterWidget.shadow": "#232323",

		"menu.background": "#171717",
		"menu.border": "#232323",
		"menu.foreground": "#fbfbfd",
		"menu.selectionBackground": "#027b3287",
		"menu.selectionBorder": "#027b3287",
		"menu.selectionForeground": "#fbfbfd",
		"menu.separatorBackground": "#232323",
		
    "menubar.selectionBackground": "#027b3287",
		"menubar.selectionBorder": "#058309a8",
		"menubar.selectionForeground": "#fbfbfd",

		"merge.border": "#232323",
		"merge.commonContentBackground": "#027b326f",
		"merge.commonHeaderBackground": "#027b3287",
		"merge.currentContentBackground": "#be000061",
		"merge.currentHeaderBackground": "#be000029",
		"merge.incomingContentBackground": "#027b3287",
		"merge.incomingHeaderBackground": "#027b3287",
		"mergeEditor.change.background": "#171717",
		"mergeEditor.change.word.background": "#171717",
		"mergeEditor.conflict.handled.minimapOverViewRuler": "#027b3287",
		"mergeEditor.conflict.handledFocused.border": "#232323",
		"mergeEditor.conflict.handledUnfocused.border": "#027b3287",
		"mergeEditor.conflict.unhandled.minimapOverViewRuler": "#0000d0",
		"mergeEditor.conflict.unhandledFocused.border": "#efe70381",
		"mergeEditor.conflict.unhandledUnfocused.border": "#232323",
		"mergeEditor.conflictingLines.background": "#be0000a8",

		"minimap.background": "#232323",
		"minimap.errorHighlight": "#be0000",
		"minimap.findMatchHighlight": "#027b327a",
		"minimap.foregroundOpacity": "#fbfbfdbc",
		"minimap.selectionHighlight": "#fbfbfd87",
		"minimap.selectionOccurrenceHighlight": "#027b3240",
		"minimap.warningHighlight": "#be0000",
		"minimapGutter.addedBackground": "#0a0ac2b4",
		"minimapGutter.deletedBackground": "#be0000",
		"minimapGutter.modifiedBackground": "#009ff5",
		"minimapSlider.activeBackground": "#fbfbfd46",
		"minimapSlider.background": "#027b323a",
		"minimapSlider.hoverBackground": "#027b3287",

		"notificationCenter.border": "#232323",
		"notificationCenterHeader.background": "#171717",
		"notificationCenterHeader.foreground": "#fbfbfd",

		"notificationLink.foreground": "#0257e0",

		"notificationToast.border": "#232323",

		"notifications.background": "#171717",
		"notifications.border": "#232323",
		"notifications.foreground": "#fbfbfd86",
		"notificationsErrorIcon.foreground": "#be00007c",
		"notificationsInfoIcon.foreground": "#003bfe",
		"notificationsWarningIcon.foreground": "#003bfe7e",

		"panel.background": "#171717",
		"panel.border": "#232323",
		"panel.dropBorder": "#fbfbfd",
		"panelInput.border": "#1e00ff",
		"panelSection.border": "#be0000",
		"panelSection.dropBackground": "#ece8e8",
		"panelSectionHeader.background": "#171717",
		"panelSectionHeader.border": "#232323",
		"panelSectionHeader.foreground": "#fbfbfd",
		"panelTitle.activeBorder": "#027b3287",
		"panelTitle.activeForeground": "#fbfbfd",
		"panelTitle.inactiveForeground": "#fbfbfd80",

		"peekView.border": "#eeff00a9",
		"peekViewEditor.background": "#171717",
		"peekViewEditor.matchHighlightBackground": "#003e0564",
		"peekViewEditor.matchHighlightBorder": "#003e0564",
		"peekViewEditorGutter.background": "#171717",
		"peekViewResult.background": "#171717",
		"peekViewResult.fileForeground": "#fbfbfd8f",
		"peekViewResult.lineForeground": "#fbfbfd",
		"peekViewResult.matchHighlightBackground": "#003e0564",
		"peekViewResult.selectionBackground": "#003e0564",
		"peekViewResult.selectionForeground": "#027b32",
		"peekViewTitle.background": "#027b3287",
		"peekViewTitleDescription.foreground": "#be0000",
		"peekViewTitleLabel.foreground": "#027b3287",

		"pickerGroup.border": "#027b3287",
		"pickerGroup.foreground": "#fbfbfd",

		"ports.iconRunningProcessForeground": "#be0000",

		"problemsErrorIcon.foreground": "#ff00000f",

		"problemsInfoIcon.foreground": "#00b3ff8c",

		"problemsWarningIcon.foreground": "#ff73008c",

		"progressBar.background": "#00eaff",

		"quickInput.background": "#171717",
		"quickInput.foreground": "#fbfbfd",
		"quickInputList.focusBackground": "#027b3287",
		"quickInputList.focusForeground": "#fbfdfb",
		"quickInputList.focusIconForeground": "#027b3287",
		"quickInputTitle.background": "#fbfbfd84",

		"sash.hoverBorder": "#027b3279",

		"scm.providerBorder": "#232323",

		"scrollbar.shadow": "#232323",

		"scrollbarSlider.activeBackground": "#232323",
		"scrollbarSlider.background": "#027b325c",
		"scrollbarSlider.hoverBackground": "#fbfbfd82",

		"searchEditor.findMatchBackground": "#93939359",
		"searchEditor.findMatchBorder": "#027b32",
		"searchEditor.textInputBorder": "#232323",

		"selection.background": "#027b3250",

		"sideBar.background": "#171717",
		"sideBar.border": "#232323",
		"sideBar.dropBackground": "#2323237f",
		"sideBar.foreground": "#fbfbfd93",
		"sideBarSectionHeader.background": "#232323",
		"sideBarSectionHeader.border": "#232323",
		"sideBarSectionHeader.foreground": "#fbfbfd70",
		"sideBarTitle.foreground": "#fbfbfd70",

		"sideBySideEditor.horizontalBorder": "#027b32",
		"sideBySideEditor.verticalBorder": "#027b32",

		"statusBar.background": "#232323",
		"statusBar.border": "#232323",
		"statusBar.debuggingBackground": "#be000064",
		"statusBar.debuggingBorder": "#9000ff71",
		"statusBar.debuggingForeground": "#fbfbfd",
		"statusBar.focusBorder": "#232323",
		"statusBar.foreground": "#fbfbfd54",
		"statusBar.noFolderBackground": "#ff6a0050",
		"statusBar.noFolderBorder": "#ff6a0050",
		"statusBar.noFolderForeground": "#fbfbfd",
		"statusBarItem.activeBackground": "#171717",
		"statusBarItem.compactHoverBackground": "#171717",
		"statusBarItem.errorBackground": "#be00006f",
		"statusBarItem.errorForeground": "#be000086",
		"statusBarItem.focusBorder": "#232323",
		"statusBarItem.hoverBackground": "#027b3287",
		"statusBarItem.prominentBackground": "#171717",
		"statusBarItem.prominentForeground": "#027b32",
		"statusBarItem.remoteBackground": "#027b3287",
		"statusBarItem.remoteForeground": "#ffffff",
		"statusBarItem.settingsProfilesBackground": "#171717",
		"statusBarItem.settingsProfilesForeground": "#fbfbfd",
		"statusBarItem.warningBackground": "#fba40196",
		"statusBarItem.warningForeground": "#0546ea7c",

		"symbolIcon.arrayForeground": "#0048ff",
		"symbolIcon.booleanForeground": "#7a00fc",
		"symbolIcon.classForeground": "#027b32",
		"symbolIcon.colorForeground": "#027b32",
		"symbolIcon.constantForeground": "#ffc803",
		"symbolIcon.constructorForeground": "#02fffb",
		"symbolIcon.enumeratorForeground": "#48bc6f",
		"symbolIcon.enumeratorMemberForeground": "#027b32",
		"symbolIcon.eventForeground": "#ff00d9",
		"symbolIcon.fieldForeground": "#be0000",
		"symbolIcon.fileForeground": "#0d00ff",
		"symbolIcon.folderForeground": "#027b3287",
		"symbolIcon.functionForeground": "#a403e4",
		"symbolIcon.interfaceForeground": "#fc0050",
		"symbolIcon.keyForeground": "#00fc48",
		"symbolIcon.keywordForeground": "#ffd501",
		"symbolIcon.methodForeground": "#ff00ae",
		"symbolIcon.moduleForeground": "#03922e",
		"symbolIcon.namespaceForeground": "#f6f202",
		"symbolIcon.nullForeground": "#323232",
		"symbolIcon.numberForeground": "#f89604",
		"symbolIcon.objectForeground": "#99ff00",
		"symbolIcon.operatorForeground": "#5555e8",
		"symbolIcon.packageForeground": "#dc00a9",
		"symbolIcon.propertyForeground": "#fbfbfd",
		"symbolIcon.referenceForeground": "#03f7ff",
		"symbolIcon.snippetForeground": "#a4a4a7",
		"symbolIcon.stringForeground": "#b0b0d7",
		"symbolIcon.structForeground": "#1f1f49",
		"symbolIcon.textForeground": "#8ead02",
		"symbolIcon.typeParameterForeground": "#6cc30f",
		"symbolIcon.unitForeground": "#1cea7f",
		"symbolIcon.variableForeground": "#fcbb06",

		"tab.activeBackground": "#171717",
		"tab.activeBorder": "#027b327b",
		"tab.activeBorderTop": "#027b3287",
		"tab.activeForeground": "#fbfbfd6c",
		"tab.activeModifiedBorder": "#027b327b",
		"tab.border": "#232323",
		"tab.hoverBackground": "#232323",
		"tab.hoverBorder": "#027b327b",
		"tab.hoverForeground": "#fbfbfd",
		"tab.inactiveBackground": "#171717",
		"tab.inactiveForeground": "#fbfbfda4",
		"tab.inactiveModifiedBorder": "#027b327b",
		"tab.lastPinnedBorder": "#232323",
		"tab.unfocusedActiveBackground": "#171717",
		"tab.unfocusedActiveBorder": "#027b3287",
		"tab.unfocusedActiveBorderTop": "#027b3287",
		"tab.unfocusedActiveForeground": "#027b3287",
		"tab.unfocusedActiveModifiedBorder": "#be0000",
		"tab.unfocusedHoverBackground": "#232323",
		"tab.unfocusedHoverBorder": "#027b327b",
		"tab.unfocusedHoverForeground": "#fbfbfd",
		"tab.unfocusedInactiveBackground": "#171717",
		"tab.unfocusedInactiveForeground": "#fbfbfda4",
		"tab.unfocusedInactiveModifiedBorder": "#be0000",

		"terminal.ansiBlack": "#077c07",
		"terminal.ansiBlue": "#00a1f9",
		"terminal.ansiBrightBlack": "#665c54",
		"terminal.ansiBrightBlue": "#0d6678",
		"terminal.ansiBrightCyan": "#8ba59b",
		"terminal.ansiBrightGreen": "#237e02",
		"terminal.ansiBrightMagenta": "#8f4673",
		"terminal.ansiBrightRed": "#be0000",
		"terminal.ansiBrightWhite": "#fdf4c1",
		"terminal.ansiBrightYellow": "#fac03b",
		"terminal.ansiCyan": "#8ba59b",
		"terminal.ansiGreen": "#027b32",
		"terminal.ansiMagenta": "#8f4673",
		"terminal.ansiRed": "#be0000",
		"terminal.ansiWhite": "#11efff",
		"terminal.ansiYellow": "#fac03b",
		"terminal.background": "#171717",
		"terminal.border": "#232323",
		"terminal.dropBackground": "#dffc005e",
		"terminal.findMatchBackground": "#027b3281",
		"terminal.findMatchBorder": "#027b32",
		"terminal.findMatchHighlightBackground": "#fef1002e",
		"terminal.findMatchHighlightBorder": "#fef10025",
		"terminal.foreground": "#6c6c6b",
		"terminal.inactiveSelectionBackground": "#40404050",
		"terminal.selectionBackground": "#027b325c",
		"terminal.selectionForeground": "#090909",
		"terminal.tab.activeBorder": "#027b32",
		"terminalCommandDecoration.defaultBackground": "#027b32",
		"terminalCommandDecoration.errorBackground": "#be0000",
		"terminalCommandDecoration.successBackground": "#171717",
		"terminalCursor.background": "#ff0000",
		"terminalCursor.foreground": "#fbfbfd",
		"terminalOverviewRuler.cursorForeground": "#027b32",
		"terminalOverviewRuler.findMatchForeground": "#027b32",

		"testing.iconErrored": "#be0000",
		"testing.iconFailed": "#be0000",
		"testing.iconPassed": "#027b32",
		"testing.iconQueued": "#ffea00",
		"testing.iconSkipped": "#ffa600",
		"testing.iconUnset": "#ff9501",
		"testing.message.error.decorationForeground": "#be0000",
		"testing.message.error.lineBackground": "#be00007e",
		"testing.message.info.decorationForeground": "#0101f98f",
		"testing.message.info.lineBackground": "#2600ff",
		"testing.peekBorder": "#171717",
		"testing.peekHeaderBackground": "#be0000",
		"testing.runAction": "#028dff",

		"textBlockQuote.background": "#027b32",
		"textBlockQuote.border": "#232323b4",

		"textCodeBlock.background": "#171717b4",

		"textLink.activeForeground": "#3e68c9",
		"textLink.foreground": "#3e68c9",

		"textPreformat.foreground": "#fbfbfd",

		"textSeparator.foreground": "#fbfbfd",

		"titleBar.activeBackground": "#171717",
		"titleBar.activeForeground": "#fbfbfd4b",
		"titleBar.border": "#0309b279",
		"titleBar.inactiveBackground": "#171717",
		"titleBar.inactiveForeground": "#fbfbfd6f",

		"toolbar.activeBackground": "#23232350",
		"toolbar.hoverBackground": "#171717",
		"toolbar.hoverOutline": "#232323",

		"tree.indentGuidesStroke": "#027b3287",
		"tree.tableColumnsBorder": "#fcfdfb",
		"tree.tableOddRowsBackground": "#232323",

		"walkThrough.embeddedEditorBackground": "#232323",

		"welcomePage.background": "#171717",
		"welcomePage.progress.background": "#232323",
		"welcomePage.progress.foreground": "#01590f91",
		"welcomePage.tileBackground": "#232323",
		"welcomePage.tileHoverBackground": "#171717",
		"welcomePage.tileShadow": "#232323",
    
		"widget.shadow": "#232323",
		"window.activeBorder": "#fbfbfd",
		"window.inactiveBorder": "#fbfbfd",
		//"debugConsole.errorForeground": "#be0000",
		//"debugConsole.infoForeground": "#0054fb",
		//"debugConsole.sourceForeground": "#fbfbfd7d",
		//"debugConsole.warningForeground": "#be0000",
		//"debugConsoleInputIcon.foreground": "#fbfbfd7d",
		//"debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
		//"debugIcon.breakpointDisabledForeground": "#848484",
		//"debugIcon.breakpointForeground": "#e51400",
		//"debugIcon.breakpointStackframeForeground": "#89d185",
		//"debugIcon.breakpointUnverifiedForeground": "#848484",
		//"debugIcon.continueForeground": "#75beff",
		//"debugIcon.disconnectForeground": "#f48771",
		//"debugIcon.pauseForeground": "#75beff",
		//"debugIcon.restartForeground": "#89d185",
		//"debugIcon.startForeground": "#89d185",
		//"debugIcon.stepBackForeground": "#75beff",
		//"debugIcon.stepIntoForeground": "#75beff",
		//"debugIcon.stepOutForeground": "#75beff",
		//"debugIcon.stepOverForeground": "#75beff",
		//"debugIcon.stopForeground": "#f48771",
		//"editorActiveLineNumber.foreground": "#c6c6c6",
		//"interactive.activeCodeBorder": "#eeff00a9",
		//"interactive.inactiveCodeBorder": "#0483023f",
		//"issues.closed": "#cb2431",
		//"issues.newIssueDecoration": "#ffffff48",
		//"issues.open": "#22863a",
		//"keybindingLabel.background": "#8080802b",
		//"notebook.cellBorderColor": "#0483023f",
		//"notebook.cellEditorBackground": "#171717",
		//"notebook.cellInsertionIndicator": "#232323",
		//"notebook.cellStatusBarItemHoverBackground": "#ffffff26",
		//"notebook.cellToolbarSeparator": "#80808059",
		//"notebook.editorBackground": "#027b32",
		//"notebook.focusedCellBorder": "#232323",
		//"notebook.focusedEditorBorder": "#232323",
		//"notebook.inactiveFocusedCellBorder": "#0483023f",
		//"notebook.selectedCellBackground": "#0483023f",
		//"notebook.selectedCellBorder": "#0483023f",
		//"notebook.symbolHighlightBackground": "#ffffff0b",
		//"notebookScrollbarSlider.activeBackground": "#232323",
		//"notebookScrollbarSlider.background": "#027b325c",
		//"notebookScrollbarSlider.hoverBackground": "#fbfbfd82",
		//"notebookStatusErrorIcon.foreground": "#be0000",
		//"notebookStatusRunningIcon.foreground": "#fbfbfd7d",
		//"notebookStatusSuccessIcon.foreground": "#89d185",
		//"pullRequests.notification": "#003bfe",
		//"settings.checkboxBackground": "#232323",
		//"settings.checkboxBorder": "#fbfbfd7e",
		//"settings.checkboxForeground": "#fbfbfd7e",
		//"settings.dropdownBackground": "#232323",
		//"settings.dropdownBorder": "#232323",
		//"settings.dropdownForeground": "#fbfbfd",
		//"settings.dropdownListBorder": "#232323",
		//"settings.focusedRowBackground": "#027b3228",
		//"settings.focusedRowBorder": "#ffffff1f",
		//"settings.headerBorder": "#232323",
		//"settings.headerForeground": "#e7e7e7",
		//"settings.modifiedItemIndicator": "#0c7d9d",
		//"settings.numberInputBackground": "#171717",
		//"settings.numberInputBorder": "#232323",
		//"settings.numberInputForeground": "#fbfbfda5",
		//"settings.rowHoverBackground": "#027b3214",
		//"settings.sashBorder": "#232323",
		//"settings.textInputBackground": "#171717",
		//"settings.textInputBorder": "#232323",
		//"settings.textInputForeground": "#fbfbfda5",
		//"statusBarItem.prominentHoverBackground": "#0000004d",
		//"notebook.cellHoverBackground": null,
		//"notebook.focusedCellBackground": null,
		//"notebook.inactiveSelectedCellBorder": null,
		//"notebook.outputContainerBackgroundColor": null,
		//"notebook.outputContainerBorderColor": null,
		//"quickInput.list.focusBackground": null

      "textLink.foreground": pick({ light: primer.blue[5], dark: primer.blue[6] }),
      "textLink.activeForeground": pick({ light: primer.blue[6], dark: primer.blue[7] }),
      "textBlockQuote.background": primer.gray[0],
      "textBlockQuote.border": primer.gray[2],
      "textCodeBlock.background": primer.gray[1],
      "textPreformat.foreground": primer.gray[6],
      "textSeparator.foreground": primer.gray[3],

      "button.background": pick({ light: "#159739", dark: primer.green[2] }),
      "button.foreground": pick({ light: primer.white, dark: primer.green[8] }),
      "button.hoverBackground": pick({ light: "#138934", dark: primer.green[3] }),

      "button.secondaryBackground": pick({ light: primer.gray[2], dark: primer.gray[2]}),
      "button.secondaryForeground": primer.black,
      "button.secondaryHoverBackground": pick({ light: primer.gray[3], dark: primer.gray[3]}),

      "checkbox.background": pick({ light: primer.gray[0], dark: primer.gray[2] }),
      "checkbox.border": pick({ light: primer.gray[3], dark: primer.white }),

      "dropdown.background": pick({ light: primer.gray[0], dark: primer.gray[1] }),
      "dropdown.border": pick({ light: primer.gray[2], dark: primer.white }),
      "dropdown.foreground": workbenchForeground,
      "dropdown.listBackground": pick({ light: primer.white, dark: primer.gray[0] }),

      "input.background": pick({ light: primer.gray[0], dark: primer.gray[1] }),
      "input.border": pick({ light: primer.gray[2], dark: primer.white }),
      "input.foreground": workbenchForeground,
      "input.placeholderForeground": pick({ light: primer.gray[4], dark: primer.gray[5] }),

      "badge.foreground": pick({ light: primer.blue[6], dark: primer.blue[7] }),
      "badge.background": pick({ light: primer.blue[1], dark: primer.blue[2] }),

      "progressBar.background": primer.blue[4],

      "titleBar.activeForeground": workbenchForeground,
      "titleBar.activeBackground": pick({ light: primer.white, dark: primer.gray[0] }),
      "titleBar.inactiveForeground": primer.gray[5],
      "titleBar.inactiveBackground": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "titleBar.border": pick({ light: primer.gray[2], dark: primer.white }),

      "activityBar.foreground": workbenchForeground,
      "activityBar.inactiveForeground": primer.gray[4],
      "activityBar.background": pick({ light: primer.white, dark: primer.gray[0] }),
      "activityBarBadge.foreground": pick({ light: primer.white, dark: primer.black }),
      "activityBarBadge.background": pick({ light: primer.blue[4], dark: primer.blue[4] }),
      "activityBar.activeBorder": "#f9826c",
      "activityBar.border": pick({ light: primer.gray[2], dark: primer.white }),

      "sideBar.foreground": primer.gray[6],
      "sideBar.background": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "sideBar.border": pick({ light: primer.gray[2], dark: primer.white }),
      "sideBarTitle.foreground": workbenchForeground,
      "sideBarSectionHeader.foreground": workbenchForeground,
      "sideBarSectionHeader.background": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "sideBarSectionHeader.border": pick({ light: primer.gray[2], dark: primer.white }),

      "list.hoverForeground": workbenchForeground,
      "list.inactiveSelectionForeground": workbenchForeground,
      "list.activeSelectionForeground": workbenchForeground,
      "list.hoverBackground": pick({ light: "#ebf0f4", dark: "#282e34" }),
      "list.inactiveSelectionBackground": pick({ light: "#e8eaed", dark: "#282e34" }),
      "list.activeSelectionBackground": pick({ light: "#e2e5e9", dark: "#39414a" }),
      "list.inactiveFocusBackground": pick({ light: primer.blue[1], dark: "#1d2d3e" }),
      "list.focusBackground": pick({ light: "#cce5ff", dark: primer.blue[2] }),

      "tree.indentGuidesStroke": pick({ light: primer.gray[2], dark: primer.gray[1] }),

      "notificationCenterHeader.foreground": primer.gray[5],
      "notificationCenterHeader.background": pick({ light: primer.gray[2], dark: primer.gray[0] }),
      "notifications.foreground": workbenchForeground,
      "notifications.background": pick({ light: primer.gray[0], dark: primer.gray[1] }),
      "notifications.border": pick({ light: primer.gray[2], dark: primer.white }),
      "notificationsErrorIcon.foreground": primer.red[5],
      "notificationsWarningIcon.foreground": primer.orange[6],
      "notificationsInfoIcon.foreground": primer.blue[6],

      "pickerGroup.border": primer.gray[2],
      "pickerGroup.foreground": workbenchForeground,
      "quickInput.background": primer.gray[0],
      "quickInput.foreground": workbenchForeground,

      "statusBar.foreground": primer.gray[6],
      "statusBar.background": pick({ light: primer.white, dark: primer.gray[0] }),
      "statusBar.border": pick({ light: primer.gray[2], dark: primer.white }),
      "statusBar.noFolderBackground": pick({ light: primer.white, dark: primer.gray[0] }),
      "statusBar.debuggingBackground": auto("#f9826c"),
      "statusBar.debuggingForeground": pick({ light: primer.white, dark: primer.black }),
      "statusBarItem.prominentBackground": pick({ light: "#e8eaed", dark: "#282e34" }),

      "editorGroupHeader.tabsBackground": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "editorGroupHeader.tabsBorder": pick({ light: primer.gray[2], dark: primer.white }),
      "editorGroup.border": pick({ light: primer.gray[2], dark: primer.white }),

      "tab.activeForeground": workbenchForeground,
      "tab.inactiveForeground": primer.gray[5],
      "tab.inactiveBackground": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "tab.activeBackground": pick({ light: primer.white, dark: primer.gray[0] }),
      "tab.hoverBackground": pick({ light: primer.white, dark: primer.gray[0] }),
      "tab.unfocusedHoverBackground": pick({ light: primer.white, dark: primer.gray[0] }),
      "tab.border": pick({ light: primer.gray[2], dark: primer.white }),
      "tab.unfocusedActiveBorderTop": pick({ light: primer.gray[2], dark: primer.white }),
      "tab.activeBorder": pick({ light: primer.white, dark: primer.gray[0] }),
      "tab.unfocusedActiveBorder": pick({ light: primer.white, dark: primer.gray[0] }),
      "tab.activeBorderTop": "#f9826c",

      "breadcrumb.foreground": primer.gray[5],
      "breadcrumb.focusForeground": workbenchForeground,
      "breadcrumb.activeSelectionForeground": primer.gray[6],
      "breadcrumbPicker.background": pick({ light: primer.gray[0], dark: "#2b3036" }),

      "editor.foreground": editorForeground,
      "editor.background": pick({ light: primer.white, dark: primer.gray[0] }),
      "editorWidget.background": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "editor.foldBackground": pick({ light: "#d1d5da11", dark: "#58606915" }), // needs opacity
      "editor.lineHighlightBackground": pick({ light: primer.gray[1], dark: "#2b3036" }),
      "editorLineNumber.foreground": pick({ light: "#1b1f234d", dark: primer.gray[2] }),
      "editorLineNumber.activeForeground": editorForeground,
      "editorIndentGuide.background": pick({ light: "#eff2f6", dark: primer.gray[1] }),
      "editorIndentGuide.activeBackground": pick({ light: "#d7dbe0", dark: primer.gray[2] }),
      "editorWhitespace.foreground": pick({ light: primer.gray[3], dark: primer.gray[2] }),
      "editorCursor.foreground": primer.blue[7],
      "editorError.foreground": primer.red[6],
      "editorWarning.foreground": primer.yellow[6],

      "editor.findMatchBackground": pick({ light: primer.yellow[4], dark: "#ffd33d44" }),
      "editor.findMatchHighlightBackground": pick({ light: "#ffdf5d66", dark: "#ffd33d22" }),
      "editor.linkedEditingBackground": pick({ light: "#0366d611", dark: "#3392FF22" }),
      "editor.inactiveSelectionBackground": pick({ light: "#0366d611", dark: "#3392FF22" }),
      "editor.selectionBackground": pick({ light: "#0366d625", dark: "#3392FF44" }),
      "editor.selectionHighlightBackground": pick({ light: "#34d05840", dark: "#17E5E633" }),
      "editor.selectionHighlightBorder": pick({ light: "#34d05800", dark: "#17E5E600" }),
      "editor.wordHighlightBackground": pick({ light: "#34d05800", dark: "#17E5E600" }),
      "editor.wordHighlightStrongBackground": pick({ light: "#34d05800", dark: "#17E5E600" }),
      "editor.wordHighlightBorder": pick({ light: "#24943e99", dark: "#17E5E699" }),
      "editor.wordHighlightStrongBorder": pick({ light: "#24943e50", dark: "#17E5E666" }),
      "editorBracketMatch.background": pick({ light: "#34d05840", dark: "#17E5E650" }),
      "editorBracketMatch.border": pick({ light: "#34d05800", dark: "#17E5E600" }),

      "editorGutter.modifiedBackground": pick({ light: primer.blue[4], dark: primer.blue[5] }),
      "editorGutter.addedBackground": pick({ light: primer.green[5], dark: primer.green[4] }),
      "editorGutter.deletedBackground": primer.red[5],

      "diffEditor.insertedTextBackground": pick({ light: "#34d05822", dark: "#28a74530" }),
      "diffEditor.removedTextBackground": pick({ light: "#d73a4922", dark: "#d73a4930" }),

      "scrollbar.shadow": pick({ light: "#6a737d33", dark: "#0008" }),
      "scrollbarSlider.background": pick({ light: "#959da533", dark: "#6a737d33" }),
      "scrollbarSlider.hoverBackground": pick({ light: "#959da544", dark: "#6a737d44" }),
      "scrollbarSlider.activeBackground": pick({ light: "#959da588", dark: "#6a737d88" }),
      "editorOverviewRuler.border": primer.white,

      "panel.background": pick({ light: primer.gray[1], dark: "#1f2428" }),
      "panel.border": pick({ light: primer.gray[2], dark: primer.white }),
      "panelTitle.activeBorder": "#f9826c",
      "panelTitle.activeForeground": workbenchForeground,
      "panelTitle.inactiveForeground": primer.gray[5],
      "panelInput.border": pick({ light: primer.gray[2], dark: primer.gray[1] }),

      "terminal.foreground": primer.gray[6],
      "terminal.tab.activeBorder": "#f9826c",
      "terminalCursor.background": primer.gray[3],
      "terminalCursor.foreground": primer.blue[6],

      // Test ANSI colors with:
      // echo -e "\033[0mNC (No color)"
      // echo -e "\033[1;37mWHITE\t\033[0;30mBLACK"
      // echo -e "\033[0;34mBLUE\t\033[1;34mLIGHT_BLUE"
      // echo -e "\033[0;32mGREEN\t\033[1;32mLIGHT_GREEN"
      // echo -e "\033[0;36mCYAN\t\033[1;36mLIGHT_CYAN"
      // echo -e "\033[0;31mRED\t\033[1;31mLIGHT_RED"
      // echo -e "\033[0;35mPURPLE\t\033[1;35mLIGHT_PURPLE"
      // echo -e "\033[0;33mYELLOW\t\033[1;33mLIGHT_YELLOW"
      // echo -e "\033[1;30mGRAY\t\033[0;37mLIGHT_GRAY"
      "terminal.ansiBrightWhite": pick({ light: primer.gray[3], dark: primer.gray[9] }), // WHITE
      "terminal.ansiWhite": pick({ light: primer.gray[5], dark: primer.gray[6] }),  // LIGHT_GRAY
      "terminal.ansiBrightBlack": pick({ light: primer.gray[4], dark: primer.gray[5] }), // GRAY
      "terminal.ansiBlack": pick({ light: primer.gray[9], dark: primer.gray[3] }), // BLACK
      "terminal.ansiBlue": primer.blue[5],
      "terminal.ansiBrightBlue": primer.blue[6],
      "terminal.ansiGreen": primer.green[5],
      "terminal.ansiBrightGreen": primer.green[6],
      "terminal.ansiCyan": pick({ light: "#1b7c83", dark: "#39c5cf" }),
      "terminal.ansiBrightCyan": pick({ light: "#3192aa", dark: "#56d4dd" }),
      "terminal.ansiRed": primer.red[5],
      "terminal.ansiBrightRed": primer.red[6],
      "terminal.ansiMagenta": primer.purple[6],
      "terminal.ansiBrightMagenta": primer.purple[6],
      "terminal.ansiYellow": pick({ light: primer.yellow[7], dark: primer.yellow[6] }),
      "terminal.ansiBrightYellow": pick({ light: primer.yellow[8], dark: primer.yellow[6] }),

      "editorBracketHighlight.foreground1": primer.blue[6],
      "editorBracketHighlight.foreground2": primer.orange[6],
      "editorBracketHighlight.foreground3": primer.purple[6],
      "editorBracketHighlight.foreground4": primer.blue[6],
      "editorBracketHighlight.foreground5": primer.orange[6],
      "editorBracketHighlight.foreground6": primer.purple[6],

      "gitDecoration.addedResourceForeground": primer.green[5],
      "gitDecoration.modifiedResourceForeground": primer.blue[6],
      "gitDecoration.deletedResourceForeground": primer.red[5],
      "gitDecoration.untrackedResourceForeground": primer.green[5],
      "gitDecoration.ignoredResourceForeground": primer.gray[4],
      "gitDecoration.conflictingResourceForeground": primer.orange[6],
      "gitDecoration.submoduleResourceForeground": primer.gray[4],

      "debugToolBar.background": pick({ light: primer.white, dark: "#2b3036" }),
      "editor.stackFrameHighlightBackground": pick({ light: "#ffd33d33", dark: "#C6902625" }), // needs opacity (yellow)
      "editor.focusedStackFrameHighlightBackground": pick({ light: "#28a74525", dark: "#2b6a3033" }), // needs opacity (green)

      "peekViewEditor.matchHighlightBackground": pick({ dark: "#ffd33d33" }),
      "peekViewResult.matchHighlightBackground": pick({ dark: "#ffd33d33" }),
      "peekViewEditor.background": pick({ dark: "#1f242888" }),
      "peekViewResult.background": pick({ dark: "#1f2428" }),

      "settings.headerForeground": workbenchForeground,
      "settings.modifiedItemIndicator": primer.blue[4],
      "welcomePage.buttonBackground": primer.gray[1],
      "welcomePage.buttonHoverBackground": primer.gray[2],
    },
    semanticHighlighting: true,
    tokenColors: [
      {
        scope: ["comment", "punctuation.definition.comment", "string.comment"],
        settings: {
          foreground: pick({ light: primer.gray[5], dark: primer.gray[4] }),
        },
      },
      {
        scope: [
          "constant",
          "entity.name.constant",
          "variable.other.constant",
          "variable.language",
        ],
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: ["entity", "entity.name"],
        settings: {
          foreground: pick({ light: primer.purple[5], dark: primer.purple[6] }),
        },
      },
      {
        scope: "variable.parameter.function",
        settings: {
          foreground: editorForeground,
        },
      },
      {
        scope: "entity.name.tag",
        settings: {
          foreground: primer.green[6],
        },
      },
      {
        scope: "keyword",
        settings: {
          foreground: pick({ light: primer.red[5], dark: primer.red[6] }),
        },
      },
      {
        scope: ["storage", "storage.type"],
        settings: {
          foreground: pick({ light: primer.red[5], dark: primer.red[6] }),
        },
      },
      {
        scope: [
          "storage.modifier.package",
          "storage.modifier.import",
          "storage.type.java",
        ],
        settings: {
          foreground: editorForeground,
        },
      },
      {
        scope: [
          "string",
          "punctuation.definition.string",
          "string punctuation.section.embedded source",
        ],
        settings: {
          foreground: pick({ light: primer.blue[8], dark: "#9ecbff" }),
        },
      },
      {
        scope: "support",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "meta.property-name",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "variable",
        settings: {
          foreground: primer.orange[6],
        },
      },
      {
        scope: "variable.other",
        settings: {
          foreground: editorForeground,
        },
      },
      {
        scope: "invalid.broken",
        settings: {
          fontStyle: "italic",
          foreground: primer.red[7],
        },
      },
      {
        scope: "invalid.deprecated",
        settings: {
          fontStyle: "italic",
          foreground: primer.red[7],
        },
      },
      {
        scope: "invalid.illegal",
        settings: {
          fontStyle: "italic",
          foreground: primer.red[7],
        },
      },
      {
        scope: "invalid.unimplemented",
        settings: {
          fontStyle: "italic",
          foreground: primer.red[7],
        },
      },
      {
        scope: "carriage-return",
        settings: {
          fontStyle: "italic underline",
          background: pick({ light: primer.red[5], dark: primer.red[6] }),
          foreground: primer.gray[0],
          content: "^M",
        },
      },
      {
        scope: "message.error",
        settings: {
          foreground: primer.red[7],
        },
      },
      {
        scope: "string source",
        settings: {
          foreground: editorForeground,
        },
      },
      {
        scope: "string variable",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: ["source.regexp", "string.regexp"],
        settings: {
          foreground: primer.blue[8],
        },
      },
      {
        scope: [
          "string.regexp.character-class",
          "string.regexp constant.character.escape",
          "string.regexp source.ruby.embedded",
          "string.regexp string.regexp.arbitrary-repitition",
        ],
        settings: {
          foreground: primer.blue[8],
        },
      },
      {
        scope: "string.regexp constant.character.escape",
        settings: {
          fontStyle: "bold",
          foreground: primer.green[6],
        },
      },
      {
        scope: "support.constant",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "support.variable",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "meta.module-reference",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "punctuation.definition.list.begin.markdown",
        settings: {
          foreground: primer.orange[6],
        },
      },
      {
        scope: ["markup.heading", "markup.heading entity.name"],
        settings: {
          fontStyle: "bold",
          foreground: primer.blue[6],
        },
      },
      {
        scope: "markup.quote",
        settings: {
          foreground: primer.green[6],
        },
      },
      {
        scope: "markup.italic",
        settings: {
          fontStyle: "italic",
          foreground: editorForeground,
        },
      },
      {
        scope: "markup.bold",
        settings: {
          fontStyle: "bold",
          foreground: editorForeground,
        },
      },
      {
        scope: "markup.raw",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: [
          "markup.deleted",
          "meta.diff.header.from-file",
          "punctuation.definition.deleted",
        ],
        settings: {
          background: primer.red[0],
          foreground: primer.red[7],
        },
      },
      {
        scope: [
          "markup.inserted",
          "meta.diff.header.to-file",
          "punctuation.definition.inserted",
        ],
        settings: {
          background: primer.green[0],
          foreground: primer.green[6],
        },
      },
      {
        scope: ["markup.changed", "punctuation.definition.changed"],
        settings: {
          background: primer.orange[1],
          foreground: primer.orange[6],
        },
      },
      {
        scope: ["markup.ignored", "markup.untracked"],
        settings: {
          foreground: primer.gray[1],
          background: primer.blue[6],
        },
      },
      {
        scope: "meta.diff.range",
        settings: {
          foreground: pick({ light: primer.purple[5], dark: primer.purple[6] }),
          fontStyle: "bold",
        },
      },
      {
        scope: "meta.diff.header",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: "meta.separator",
        settings: {
          fontStyle: "bold",
          foreground: primer.blue[6],
        },
      },
      {
        scope: "meta.output",
        settings: {
          foreground: primer.blue[6],
        },
      },
      {
        scope: [
          "brackethighlighter.tag",
          "brackethighlighter.curly",
          "brackethighlighter.round",
          "brackethighlighter.square",
          "brackethighlighter.angle",
          "brackethighlighter.quote",
        ],
        settings: {
          foreground: primer.gray[6],
        },
      },
      {
        scope: "brackethighlighter.unmatched",
        settings: {
          foreground: primer.red[7],
        },
      },
      {
        scope: ["constant.other.reference.link", "string.other.link"],
        settings: {
          foreground: primer.blue[8],
          fontStyle: "underline",
        },
      },
    ],
  };
}

module.exports = getTheme;
